const canciones = [
  {
    title: "Small Worlds",
    artist: "Mac Miller",
    genre: "Hip-Hop",
    duration: 5.47,
    year: 2023,
    isHit: true,
  },
  {
    title: "Soul Kitchen",
    artist: "The Doors",
    genre: "Rock",
    duration: 3.3,
    year: 1967,
    isHit: false,
  },
  {
    title: "Clash City Rockers",
    artist: "The Clash",
    genre: "Rock",
    duration: 2.24,
    year: 1979,
    isHit: false,
  },
  {
    title: "Conception",
    artist: "Miles Davis",
    genre: "Jazz",
    duration: 3.03,
    year: 1951,
    isHit: true,
  },
  {
    title: "Is This It",
    artist: "The Strokes",
    genre: "Rock",
    duration: 2.3,
    year: 2001,
    isHit: true,
  },
  {
    title: "Gin And Juice",
    artist: "Snoop Doggy Dogg",
    genre: "Hip Hop",
    duration: 4.04,
    year: 1993,
    isHit: false,
  },
];
